# Generated by Django 5.1.3 on 2024-11-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MNStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp', models.FloatField()),
                ('Hum', models.FloatField()),
                ('Volt', models.FloatField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
