# Generated by Django 5.1.3 on 2024-11-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mnstatus',
            old_name='Hum',
            new_name='Humi',
        ),
    ]
