# Generated by Django 5.1.3 on 2024-11-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_hum_mnstatus_humi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MNSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TelegramToken', models.IntegerField()),
                ('TelegramChatId', models.IntegerField()),
                ('TempAlert', models.IntegerField()),
                ('TempStatus', models.IntegerField()),
                ('HumiAlert', models.IntegerField()),
                ('HumiStatus', models.IntegerField()),
                ('VoltAlert', models.IntegerField()),
                ('VoltStatus', models.IntegerField()),
            ],
        ),
    ]
