# Generated by Django 5.1.3 on 2024-11-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mnsetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mnsetup',
            name='TelegramChatId',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='mnsetup',
            name='TelegramToken',
            field=models.CharField(max_length=46),
        ),
    ]
